import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });      // fonts

export const metadata: Metadata = {               // meta data for SEO
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className="p-4 border">    {/* act like as an appbar */}
          Medium Website Appbar
        </div>

        {children}</body>     {/* what is called */}
    </html>
  );
}
